
default: &default
  adapter: postgresql
  encoding: unicode
  prepared_statements: false

development:
  <<: *default
  database: timeclock_dev
  pool: 5
  username: 
  password:

test:
  <<: *default
  database: timeclock_test
  pool: 5
  username: 
  password:

production:
  <<: *default
  url:  <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['DB_POOL'] || ENV['MAX_THREADS'] || 5 %>
